### ISSUE TITLE
Add Windows 11 Widgets to cations 

### ISSUE THREAD

**Issue by wanderseeme** [flexits/HotCornersWin#18]
I find Windows 11 Widgets quite useful recently, would be great if you add Widgets action to the action list!

It's quite hard for me to custom this Widgets action, I could not find the corresponding shell command :-(

**Comment by flexits** [comment]
> add Widgets action

I'm not (yet) a Windows 11 user, could you explain WDYM by that? Show the Widgets panel, I guess?

**Comment by flexits** [comment]
added
