### ISSUE TITLE
The hot zone is ineffective in full-screen mode of VMware Horizon Client

### ISSUE THREAD

**Issue by xeahsoon** [flexits/HotCornersWin#19]
When using VMware Horizon Client to remotely access other desktops and turn on full screen, there is no response when the mouse is moved to the corner. I have tried another tool, winxcorners. This tool works normally in my scenario. Perhaps it can be referenced to solve this problem.

**Comment by xeahsoon** [comment]
Add another question: The lock screen action is also ineffective. My system version is Windows 10 Professional Edition 22H2.

**Comment by flexits** [comment]
> VMware Horizon Client to remotely access other desktops and turn on full screen

Is "Turn off if a fullscreen app is opened" checked in the app's Settings?

**Comment by xeahsoon** [comment]
> > VMware Horizon Client to remotely access other desktops and turn on full screen
> 
> Is "Turn off if a fullscreen app is opened" checked in the app's Settings?

This setting is not checked. I have tried repeatedly modifying this setting, but it has no effect.

**Comment by xeahsoon** [comment]
@flexits I know what happened. When using VMware Horizon Client for remote desktop, the shortcut key "Ctrl+Win+Left" used by the "Left Virtual Desktop" action is sent to the remote system. Therefore, it cannot jump to the main desktop normally. If custom shortcut keys are supported, this problem can be solved by setting two sets of shortcut keys: "Ctrl+Alt,Ctrl+Win+Left".

**Comment by xeahsoon** [comment]
At present, I have to execute external program calls to shortcut keys through Custom Action. For specific programs, you can refer to https://github.com/xeahsoon/keyboard-simulator. However, I still hope this function can be integrated into HotCornersWin.

**Comment by flexits** [comment]
> The lock screen action is also ineffective

Hotkeys weren't processed in a correct way; utilized `LockWorkStation` method of `user32.dll` instead.
Fixed in [beta 0.8.7](https://github.com/flexits/HotCornersWin/releases/tag/v0.8.7).

**Comment by flexits** [comment]
> If custom shortcut keys are supported, this problem can be solved by setting two sets of shortcut keys: "Ctrl+Alt,Ctrl+Win+Left".

> At present, I have to execute external program calls to shortcut keys through Custom Action. For specific programs, you can refer to https://github.com/xeahsoon/keyboard-simulator. However, I still hope this function can be integrated into HotCornersWin.

Referenced in related issue #6 
Closing this as duplicate.
