### ISSUE TITLE
Pop Error window after lock screen

### ISSUE THREAD

**Issue by VA5811** [flexits/HotCornersWin#21]
Platform: windows 10 x64

Move mouse to corner to lock screen: OK
unlock screen: OK, but many windows of ERROR are on the desktop. Need to close one by one.

Reason ( I guess ): the progress still calls rundll32.exe to lock screen after screen was locked, because the location of mouse is in the corner.
Advice: Add "if" to check whether the screen was locked. If the screen was locked, DO NOT call rundll32.exe to lock workstation.

**Comment by VA5811** [comment]
After unlocking the locked screen, I noticed a large number of pop-ups displaying "error"

**Comment by flexits** [comment]
> I noticed a large number of pop-ups displaying "error"

What exactly do these pop-ups read? What error (code, text, or something)? 

I'll have a look later.

**Comment by VA5811** [comment]
> > I noticed a large number of pop-ups displaying "error"
> 
> What exactly do these pop-ups read? What error (code, text, or something)?
> 
> I'll have a look later.

My Language is Chinese. Pop-ups display "拒绝访问" which means "access denied" or "deny access".

**Comment by flexits** [comment]
I failed to reproduce this behavior on my PC.

**Comment by flexits** [comment]
No details provided; the problem isn't reproducible on any of my PCs. Seems to be unrelated to the software. 
Feel free to open a new issue with more detail on this error if still experiencing it.

**Comment by flexits** [comment]
No details provided; the problem isn't reproducible on any of my PCs. Seems to be unrelated to the software. 
Feel free to open a new issue with more detail on this error if still experiencing it.
